global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["localhost:9093"]

scrape_configs:
  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Scrape Node Exporter (system metrics: CPU, memory, disk, etc.)
  - job_name: "node_exporter"
    static_configs:
      - targets: ["localhost:9100"]

  # Scrape Blackbox Exporter to check React App availability
  - job_name: "react-app-availability"
    metrics_path: /probe
    params:
      module: [http_2xx]  # checks HTTP 200 response
    static_configs:
      - targets:
          - http://13.60.189.24  # React app public URL
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115  # Blackbox Exporter address

  # Scrape Blackbox Exporter itself
  - job_name: "blackbox_exporter"
    static_configs:
      - targets: ["localhost:9115"]
